name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: 16
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Clean install dependencies
        run: yarn install
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build app
        run: yarn run build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'